// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P_Galchis_Cristian.Data;

#nullable disable

namespace P_Galchis_Cristian.Migrations
{
    [DbContext(typeof(P_Galchis_CristianContext))]
    [Migration("20241229215743_AddStilDoi")]
    partial class AddStilDoi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P_Galchis_Cristian.Models.Bilet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ClientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ObiectivID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ClientID");

                    b.HasIndex("ObiectivID");

                    b.ToTable("Bilet");
                });

            modelBuilder.Entity("P_Galchis_Cristian.Models.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("P_Galchis_Cristian.Models.Obiectiv", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Orar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<int>("StilID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StilID");

                    b.ToTable("Obiectiv");
                });

            modelBuilder.Entity("P_Galchis_Cristian.Models.Stil", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Stil");
                });

            modelBuilder.Entity("P_Galchis_Cristian.Models.Bilet", b =>
                {
                    b.HasOne("P_Galchis_Cristian.Models.Client", "Client")
                        .WithMany("Bilete")
                        .HasForeignKey("ClientID");

                    b.HasOne("P_Galchis_Cristian.Models.Obiectiv", "Obiectiv")
                        .WithMany("Bilete")
                        .HasForeignKey("ObiectivID");

                    b.Navigation("Client");

                    b.Navigation("Obiectiv");
                });

            modelBuilder.Entity("P_Galchis_Cristian.Models.Obiectiv", b =>
                {
                    b.HasOne("P_Galchis_Cristian.Models.Stil", "Stil")
                        .WithMany("Obiective")
                        .HasForeignKey("StilID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stil");
                });

            modelBuilder.Entity("P_Galchis_Cristian.Models.Client", b =>
                {
                    b.Navigation("Bilete");
                });

            modelBuilder.Entity("P_Galchis_Cristian.Models.Obiectiv", b =>
                {
                    b.Navigation("Bilete");
                });

            modelBuilder.Entity("P_Galchis_Cristian.Models.Stil", b =>
                {
                    b.Navigation("Obiective");
                });
#pragma warning restore 612, 618
        }
    }
}
